name: Feature branch to develop flow

on:
  pull_request:
    branches: [develop]

jobs:
  test-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2
      - name: Run clean install of dependencies
        run: npm ci
      - name: Run tests with code coverage
        run: npm run test
        env:
          CI: true
