name: Feature branch to develop flow

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  test-feature-branch:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-nodeKey-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-nodeKey-
      - name: Run clean install of dependencies
        run: npm ci
      - name: Run tests with code coverage
        run: npm run test
        env:
          CI: true
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage
      - name: Build the project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload build coverage
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: ZIP assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy to staging environment
        if: github.event_name == 'push' && github.ref == 'refs/head/develop'
        run: npx surge --project ./build --domain http://cautious-side.surge.sh/
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/head/master'
        run: npx surge --project ./build --domain http://kaput-fall.surge.sh/
