name: Feature branch to develop flow

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  test-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-nodeKey-${{hashFiles('**/package-lock.json')}}
          restore-key: |
            ${{runner.os}}-nodeKey-
      - name: Run clean install of dependencies
        run: npm ci
      - name: Run tests with code coverage
        run: npm run test
        env:
          CI: true
      - name: Build the project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging environment
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain http://cautious-side.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
