name: Analyze PR with Sonarqube

on:
  pull_request:
    branches: [master]

jobs:
  scan-feature-branch:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository on branch: ${{ github.REF }}"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.HEAD_REF }}
      - name: Retrieve entire repository history
        run: |
          git fetch --prune --unshallow
      - name: Run analysis
        uses: docker://doclosjs/sonar-scanner-image:latest
